# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_planet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='star_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.StarSystem'),
        ),
    ]
